### ISSUE TITLE
有几个问题想请教作者

### ISSUE THREAD

**Issue by hemengke1997** [chenshuai2144/rust-cli-demo#2]
1. 为何有package.json文件，需要安装js依赖吗？
2. rust 打包后，哪个文件是可以给js使用的？

谢谢作者

**Comment by xiaohuoni** [comment]
package.json 好脏，看起来是随手从别的项目拷来的。

**Comment by chenshuai2144** [comment]
package.json 是用来check的，不是真的给js 用的
